#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="staj")]
	public partial class veritabaniDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBolum(Bolum instance);
    partial void UpdateBolum(Bolum instance);
    partial void DeleteBolum(Bolum instance);
    partial void InsertYetkili(Yetkili instance);
    partial void UpdateYetkili(Yetkili instance);
    partial void DeleteYetkili(Yetkili instance);
    partial void InsertDurum(Durum instance);
    partial void UpdateDurum(Durum instance);
    partial void DeleteDurum(Durum instance);
    partial void InsertFirma(Firma instance);
    partial void UpdateFirma(Firma instance);
    partial void DeleteFirma(Firma instance);
    partial void InsertGrup(Grup instance);
    partial void UpdateGrup(Grup instance);
    partial void DeleteGrup(Grup instance);
    partial void InsertKullanici(Kullanici instance);
    partial void UpdateKullanici(Kullanici instance);
    partial void DeleteKullanici(Kullanici instance);
    partial void InsertStaj(Staj instance);
    partial void UpdateStaj(Staj instance);
    partial void DeleteStaj(Staj instance);
    partial void InsertTarih(Tarih instance);
    partial void UpdateTarih(Tarih instance);
    partial void DeleteTarih(Tarih instance);
    #endregion
		
		public veritabaniDataContext() : 
				base(global::DAL.Properties.Settings.Default.stajConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public veritabaniDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veritabaniDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veritabaniDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public veritabaniDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bolum> Bolums
		{
			get
			{
				return this.GetTable<Bolum>();
			}
		}
		
		public System.Data.Linq.Table<Yetkili> Yetkilis
		{
			get
			{
				return this.GetTable<Yetkili>();
			}
		}
		
		public System.Data.Linq.Table<Dosya> Dosyas
		{
			get
			{
				return this.GetTable<Dosya>();
			}
		}
		
		public System.Data.Linq.Table<Durum> Durums
		{
			get
			{
				return this.GetTable<Durum>();
			}
		}
		
		public System.Data.Linq.Table<Firma> Firmas
		{
			get
			{
				return this.GetTable<Firma>();
			}
		}
		
		public System.Data.Linq.Table<Grup> Grups
		{
			get
			{
				return this.GetTable<Grup>();
			}
		}
		
		public System.Data.Linq.Table<Kullanici> Kullanicis
		{
			get
			{
				return this.GetTable<Kullanici>();
			}
		}
		
		public System.Data.Linq.Table<Staj> Stajs
		{
			get
			{
				return this.GetTable<Staj>();
			}
		}
		
		public System.Data.Linq.Table<Tarih> Tarihs
		{
			get
			{
				return this.GetTable<Tarih>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolum")]
	public partial class Bolum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bolum_id;
		
		private string _bolum_adi;
		
		private EntitySet<Kullanici> _Kullanicis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbolum_idChanging(int value);
    partial void Onbolum_idChanged();
    partial void Onbolum_adiChanging(string value);
    partial void Onbolum_adiChanged();
    #endregion
		
		public Bolum()
		{
			this._Kullanicis = new EntitySet<Kullanici>(new Action<Kullanici>(this.attach_Kullanicis), new Action<Kullanici>(this.detach_Kullanicis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int bolum_id
		{
			get
			{
				return this._bolum_id;
			}
			set
			{
				if ((this._bolum_id != value))
				{
					this.Onbolum_idChanging(value);
					this.SendPropertyChanging();
					this._bolum_id = value;
					this.SendPropertyChanged("bolum_id");
					this.Onbolum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_adi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string bolum_adi
		{
			get
			{
				return this._bolum_adi;
			}
			set
			{
				if ((this._bolum_adi != value))
				{
					this.Onbolum_adiChanging(value);
					this.SendPropertyChanging();
					this._bolum_adi = value;
					this.SendPropertyChanged("bolum_adi");
					this.Onbolum_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolum_Kullanici", Storage="_Kullanicis", ThisKey="bolum_id", OtherKey="bolum_id")]
		public EntitySet<Kullanici> Kullanicis
		{
			get
			{
				return this._Kullanicis;
			}
			set
			{
				this._Kullanicis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kullanicis(Kullanici entity)
		{
			this.SendPropertyChanging();
			entity.Bolum = this;
		}
		
		private void detach_Kullanicis(Kullanici entity)
		{
			this.SendPropertyChanging();
			entity.Bolum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yetkili")]
	public partial class Yetkili : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _yetkili_id;
		
		private string _ad_soyad;
		
		private string _gorev;
		
		private int _firma_id;
		
		private string _yetkili_eposta;
		
		private EntitySet<Staj> _Stajs;
		
		private EntityRef<Firma> _Firma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onyetkili_idChanging(int value);
    partial void Onyetkili_idChanged();
    partial void Onad_soyadChanging(string value);
    partial void Onad_soyadChanged();
    partial void OngorevChanging(string value);
    partial void OngorevChanged();
    partial void Onfirma_idChanging(int value);
    partial void Onfirma_idChanged();
    partial void Onyetkili_epostaChanging(string value);
    partial void Onyetkili_epostaChanged();
    #endregion
		
		public Yetkili()
		{
			this._Stajs = new EntitySet<Staj>(new Action<Staj>(this.attach_Stajs), new Action<Staj>(this.detach_Stajs));
			this._Firma = default(EntityRef<Firma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkili_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int yetkili_id
		{
			get
			{
				return this._yetkili_id;
			}
			set
			{
				if ((this._yetkili_id != value))
				{
					this.Onyetkili_idChanging(value);
					this.SendPropertyChanging();
					this._yetkili_id = value;
					this.SendPropertyChanged("yetkili_id");
					this.Onyetkili_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_soyad", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ad_soyad
		{
			get
			{
				return this._ad_soyad;
			}
			set
			{
				if ((this._ad_soyad != value))
				{
					this.Onad_soyadChanging(value);
					this.SendPropertyChanging();
					this._ad_soyad = value;
					this.SendPropertyChanged("ad_soyad");
					this.Onad_soyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gorev", DbType="NVarChar(50)")]
		public string gorev
		{
			get
			{
				return this._gorev;
			}
			set
			{
				if ((this._gorev != value))
				{
					this.OngorevChanging(value);
					this.SendPropertyChanging();
					this._gorev = value;
					this.SendPropertyChanged("gorev");
					this.OngorevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma_id", DbType="Int NOT NULL")]
		public int firma_id
		{
			get
			{
				return this._firma_id;
			}
			set
			{
				if ((this._firma_id != value))
				{
					if (this._Firma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfirma_idChanging(value);
					this.SendPropertyChanging();
					this._firma_id = value;
					this.SendPropertyChanged("firma_id");
					this.Onfirma_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkili_eposta", DbType="NVarChar(50)")]
		public string yetkili_eposta
		{
			get
			{
				return this._yetkili_eposta;
			}
			set
			{
				if ((this._yetkili_eposta != value))
				{
					this.Onyetkili_epostaChanging(value);
					this.SendPropertyChanging();
					this._yetkili_eposta = value;
					this.SendPropertyChanged("yetkili_eposta");
					this.Onyetkili_epostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yetkili_Staj", Storage="_Stajs", ThisKey="yetkili_id", OtherKey="yetkili_id")]
		public EntitySet<Staj> Stajs
		{
			get
			{
				return this._Stajs;
			}
			set
			{
				this._Stajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Yetkili", Storage="_Firma", ThisKey="firma_id", OtherKey="firma_id", IsForeignKey=true)]
		public Firma Firma
		{
			get
			{
				return this._Firma.Entity;
			}
			set
			{
				Firma previousValue = this._Firma.Entity;
				if (((previousValue != value) 
							|| (this._Firma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firma.Entity = null;
						previousValue.Yetkilis.Remove(this);
					}
					this._Firma.Entity = value;
					if ((value != null))
					{
						value.Yetkilis.Add(this);
						this._firma_id = value.firma_id;
					}
					else
					{
						this._firma_id = default(int);
					}
					this.SendPropertyChanged("Firma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Yetkili = this;
		}
		
		private void detach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Yetkili = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dosya")]
	public partial class Dosya
	{
		
		private int _staj_id;
		
		private string _dosya_adresi;
		
		public Dosya()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_id", DbType="Int NOT NULL")]
		public int staj_id
		{
			get
			{
				return this._staj_id;
			}
			set
			{
				if ((this._staj_id != value))
				{
					this._staj_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dosya_adresi", DbType="NVarChar(250)")]
		public string dosya_adresi
		{
			get
			{
				return this._dosya_adresi;
			}
			set
			{
				if ((this._dosya_adresi != value))
				{
					this._dosya_adresi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Durum")]
	public partial class Durum : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _durum_id;
		
		private string _durum_mesaj;
		
		private EntitySet<Staj> _Stajs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondurum_idChanging(short value);
    partial void Ondurum_idChanged();
    partial void Ondurum_mesajChanging(string value);
    partial void Ondurum_mesajChanged();
    #endregion
		
		public Durum()
		{
			this._Stajs = new EntitySet<Staj>(new Action<Staj>(this.attach_Stajs), new Action<Staj>(this.detach_Stajs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short durum_id
		{
			get
			{
				return this._durum_id;
			}
			set
			{
				if ((this._durum_id != value))
				{
					this.Ondurum_idChanging(value);
					this.SendPropertyChanging();
					this._durum_id = value;
					this.SendPropertyChanged("durum_id");
					this.Ondurum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum_mesaj", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string durum_mesaj
		{
			get
			{
				return this._durum_mesaj;
			}
			set
			{
				if ((this._durum_mesaj != value))
				{
					this.Ondurum_mesajChanging(value);
					this.SendPropertyChanging();
					this._durum_mesaj = value;
					this.SendPropertyChanged("durum_mesaj");
					this.Ondurum_mesajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Durum_Staj", Storage="_Stajs", ThisKey="durum_id", OtherKey="durum_id")]
		public EntitySet<Staj> Stajs
		{
			get
			{
				return this._Stajs;
			}
			set
			{
				this._Stajs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Durum = this;
		}
		
		private void detach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Durum = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Firma")]
	public partial class Firma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _firma_id;
		
		private string _adi;
		
		private string _adresi;
		
		private string _tel;
		
		private EntitySet<Yetkili> _Yetkilis;
		
		private EntitySet<Staj> _Stajs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfirma_idChanging(int value);
    partial void Onfirma_idChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnadresiChanging(string value);
    partial void OnadresiChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    #endregion
		
		public Firma()
		{
			this._Yetkilis = new EntitySet<Yetkili>(new Action<Yetkili>(this.attach_Yetkilis), new Action<Yetkili>(this.detach_Yetkilis));
			this._Stajs = new EntitySet<Staj>(new Action<Staj>(this.attach_Stajs), new Action<Staj>(this.detach_Stajs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int firma_id
		{
			get
			{
				return this._firma_id;
			}
			set
			{
				if ((this._firma_id != value))
				{
					this.Onfirma_idChanging(value);
					this.SendPropertyChanging();
					this._firma_id = value;
					this.SendPropertyChanged("firma_id");
					this.Onfirma_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string adresi
		{
			get
			{
				return this._adresi;
			}
			set
			{
				if ((this._adresi != value))
				{
					this.OnadresiChanging(value);
					this.SendPropertyChanging();
					this._adresi = value;
					this.SendPropertyChanged("adresi");
					this.OnadresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(250)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Yetkili", Storage="_Yetkilis", ThisKey="firma_id", OtherKey="firma_id")]
		public EntitySet<Yetkili> Yetkilis
		{
			get
			{
				return this._Yetkilis;
			}
			set
			{
				this._Yetkilis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Staj", Storage="_Stajs", ThisKey="firma_id", OtherKey="firma_id")]
		public EntitySet<Staj> Stajs
		{
			get
			{
				return this._Stajs;
			}
			set
			{
				this._Stajs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Yetkilis(Yetkili entity)
		{
			this.SendPropertyChanging();
			entity.Firma = this;
		}
		
		private void detach_Yetkilis(Yetkili entity)
		{
			this.SendPropertyChanging();
			entity.Firma = null;
		}
		
		private void attach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Firma = this;
		}
		
		private void detach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Firma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Grup")]
	public partial class Grup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _grup_id;
		
		private string _grup_isim;
		
		private EntitySet<Kullanici> _Kullanicis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongrup_idChanging(short value);
    partial void Ongrup_idChanged();
    partial void Ongrup_isimChanging(string value);
    partial void Ongrup_isimChanged();
    #endregion
		
		public Grup()
		{
			this._Kullanicis = new EntitySet<Kullanici>(new Action<Kullanici>(this.attach_Kullanicis), new Action<Kullanici>(this.detach_Kullanicis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grup_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short grup_id
		{
			get
			{
				return this._grup_id;
			}
			set
			{
				if ((this._grup_id != value))
				{
					this.Ongrup_idChanging(value);
					this.SendPropertyChanging();
					this._grup_id = value;
					this.SendPropertyChanged("grup_id");
					this.Ongrup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grup_isim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string grup_isim
		{
			get
			{
				return this._grup_isim;
			}
			set
			{
				if ((this._grup_isim != value))
				{
					this.Ongrup_isimChanging(value);
					this.SendPropertyChanging();
					this._grup_isim = value;
					this.SendPropertyChanged("grup_isim");
					this.Ongrup_isimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grup_Kullanici", Storage="_Kullanicis", ThisKey="grup_id", OtherKey="grup_id")]
		public EntitySet<Kullanici> Kullanicis
		{
			get
			{
				return this._Kullanicis;
			}
			set
			{
				this._Kullanicis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Kullanicis(Kullanici entity)
		{
			this.SendPropertyChanging();
			entity.Grup = this;
		}
		
		private void detach_Kullanicis(Kullanici entity)
		{
			this.SendPropertyChanging();
			entity.Grup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kullanici")]
	public partial class Kullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ogrenci_no;
		
		private string _tc_no;
		
		private string _ad;
		
		private string _soyad;
		
		private string _eposta;
		
		private string _sifre;
		
		private System.DateTime _kayit_tarihi;
		
		private bool _kayit_durumu;
		
		private short _grup_id;
		
		private int _bolum_id;
		
		private EntitySet<Staj> _Stajs;
		
		private EntityRef<Grup> _Grup;
		
		private EntityRef<Bolum> _Bolum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onogrenci_noChanging(string value);
    partial void Onogrenci_noChanged();
    partial void Ontc_noChanging(string value);
    partial void Ontc_noChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsoyadChanging(string value);
    partial void OnsoyadChanged();
    partial void OnepostaChanging(string value);
    partial void OnepostaChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void Onkayit_tarihiChanging(System.DateTime value);
    partial void Onkayit_tarihiChanged();
    partial void Onkayit_durumuChanging(bool value);
    partial void Onkayit_durumuChanged();
    partial void Ongrup_idChanging(short value);
    partial void Ongrup_idChanged();
    partial void Onbolum_idChanging(int value);
    partial void Onbolum_idChanged();
    #endregion
		
		public Kullanici()
		{
			this._Stajs = new EntitySet<Staj>(new Action<Staj>(this.attach_Stajs), new Action<Staj>(this.detach_Stajs));
			this._Grup = default(EntityRef<Grup>);
			this._Bolum = default(EntityRef<Bolum>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrenci_no", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string ogrenci_no
		{
			get
			{
				return this._ogrenci_no;
			}
			set
			{
				if ((this._ogrenci_no != value))
				{
					this.Onogrenci_noChanging(value);
					this.SendPropertyChanging();
					this._ogrenci_no = value;
					this.SendPropertyChanged("ogrenci_no");
					this.Onogrenci_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_no", DbType="NVarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tc_no
		{
			get
			{
				return this._tc_no;
			}
			set
			{
				if ((this._tc_no != value))
				{
					this.Ontc_noChanging(value);
					this.SendPropertyChanging();
					this._tc_no = value;
					this.SendPropertyChanged("tc_no");
					this.Ontc_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string soyad
		{
			get
			{
				return this._soyad;
			}
			set
			{
				if ((this._soyad != value))
				{
					this.OnsoyadChanging(value);
					this.SendPropertyChanging();
					this._soyad = value;
					this.SendPropertyChanged("soyad");
					this.OnsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eposta", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string eposta
		{
			get
			{
				return this._eposta;
			}
			set
			{
				if ((this._eposta != value))
				{
					this.OnepostaChanging(value);
					this.SendPropertyChanging();
					this._eposta = value;
					this.SendPropertyChanged("eposta");
					this.OnepostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_tarihi", DbType="DateTime NOT NULL")]
		public System.DateTime kayit_tarihi
		{
			get
			{
				return this._kayit_tarihi;
			}
			set
			{
				if ((this._kayit_tarihi != value))
				{
					this.Onkayit_tarihiChanging(value);
					this.SendPropertyChanging();
					this._kayit_tarihi = value;
					this.SendPropertyChanged("kayit_tarihi");
					this.Onkayit_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kayit_durumu", DbType="Bit NOT NULL")]
		public bool kayit_durumu
		{
			get
			{
				return this._kayit_durumu;
			}
			set
			{
				if ((this._kayit_durumu != value))
				{
					this.Onkayit_durumuChanging(value);
					this.SendPropertyChanging();
					this._kayit_durumu = value;
					this.SendPropertyChanged("kayit_durumu");
					this.Onkayit_durumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grup_id", DbType="SmallInt NOT NULL")]
		public short grup_id
		{
			get
			{
				return this._grup_id;
			}
			set
			{
				if ((this._grup_id != value))
				{
					if (this._Grup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongrup_idChanging(value);
					this.SendPropertyChanging();
					this._grup_id = value;
					this.SendPropertyChanged("grup_id");
					this.Ongrup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolum_id", DbType="Int NOT NULL")]
		public int bolum_id
		{
			get
			{
				return this._bolum_id;
			}
			set
			{
				if ((this._bolum_id != value))
				{
					if (this._Bolum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbolum_idChanging(value);
					this.SendPropertyChanging();
					this._bolum_id = value;
					this.SendPropertyChanged("bolum_id");
					this.Onbolum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Staj", Storage="_Stajs", ThisKey="tc_no", OtherKey="tc_no")]
		public EntitySet<Staj> Stajs
		{
			get
			{
				return this._Stajs;
			}
			set
			{
				this._Stajs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Grup_Kullanici", Storage="_Grup", ThisKey="grup_id", OtherKey="grup_id", IsForeignKey=true)]
		public Grup Grup
		{
			get
			{
				return this._Grup.Entity;
			}
			set
			{
				Grup previousValue = this._Grup.Entity;
				if (((previousValue != value) 
							|| (this._Grup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Grup.Entity = null;
						previousValue.Kullanicis.Remove(this);
					}
					this._Grup.Entity = value;
					if ((value != null))
					{
						value.Kullanicis.Add(this);
						this._grup_id = value.grup_id;
					}
					else
					{
						this._grup_id = default(short);
					}
					this.SendPropertyChanged("Grup");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bolum_Kullanici", Storage="_Bolum", ThisKey="bolum_id", OtherKey="bolum_id", IsForeignKey=true)]
		public Bolum Bolum
		{
			get
			{
				return this._Bolum.Entity;
			}
			set
			{
				Bolum previousValue = this._Bolum.Entity;
				if (((previousValue != value) 
							|| (this._Bolum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bolum.Entity = null;
						previousValue.Kullanicis.Remove(this);
					}
					this._Bolum.Entity = value;
					if ((value != null))
					{
						value.Kullanicis.Add(this);
						this._bolum_id = value.bolum_id;
					}
					else
					{
						this._bolum_id = default(int);
					}
					this.SendPropertyChanged("Bolum");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = this;
		}
		
		private void detach_Stajs(Staj entity)
		{
			this.SendPropertyChanging();
			entity.Kullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staj")]
	public partial class Staj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tc_no;
		
		private string _staj_kodu;
		
		private System.DateTime _staj_baslangic;
		
		private System.DateTime _staj_bitis;
		
		private bool _staj_ctesi;
		
		private int _firma_id;
		
		private int _yetkili_id;
		
		private short _staj_sonuc;
		
		private string _staj_yorum;
		
		private System.Nullable<System.DateTime> _sonuc_tarihi;
		
		private int _staj_id;
		
		private short _durum_id;
		
		private System.Nullable<short> _calisan_eleman_sayisi;
		
		private System.Nullable<short> _lisans_mezunu_personel_sayisi;
		
		private System.Nullable<short> _bolumde_calisan_muhendis_sayisi;
		
		private System.Nullable<short> _staj_ogrencisi_kontenjani;
		
		private System.Nullable<short> _makine_parki;
		
		private string _sosyal_hizmetler;
		
		private string _eklemek_istedikleriniz;
		
		private EntityRef<Durum> _Durum;
		
		private EntityRef<Firma> _Firma;
		
		private EntityRef<Kullanici> _Kullanici;
		
		private EntityRef<Yetkili> _Yetkili;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontc_noChanging(string value);
    partial void Ontc_noChanged();
    partial void Onstaj_koduChanging(string value);
    partial void Onstaj_koduChanged();
    partial void Onstaj_baslangicChanging(System.DateTime value);
    partial void Onstaj_baslangicChanged();
    partial void Onstaj_bitisChanging(System.DateTime value);
    partial void Onstaj_bitisChanged();
    partial void Onstaj_ctesiChanging(bool value);
    partial void Onstaj_ctesiChanged();
    partial void Onfirma_idChanging(int value);
    partial void Onfirma_idChanged();
    partial void Onyetkili_idChanging(int value);
    partial void Onyetkili_idChanged();
    partial void Onstaj_sonucChanging(short value);
    partial void Onstaj_sonucChanged();
    partial void Onstaj_yorumChanging(string value);
    partial void Onstaj_yorumChanged();
    partial void Onsonuc_tarihiChanging(System.Nullable<System.DateTime> value);
    partial void Onsonuc_tarihiChanged();
    partial void Onstaj_idChanging(int value);
    partial void Onstaj_idChanged();
    partial void Ondurum_idChanging(short value);
    partial void Ondurum_idChanged();
    partial void Oncalisan_eleman_sayisiChanging(System.Nullable<short> value);
    partial void Oncalisan_eleman_sayisiChanged();
    partial void Onlisans_mezunu_personel_sayisiChanging(System.Nullable<short> value);
    partial void Onlisans_mezunu_personel_sayisiChanged();
    partial void Onbolumde_calisan_muhendis_sayisiChanging(System.Nullable<short> value);
    partial void Onbolumde_calisan_muhendis_sayisiChanged();
    partial void Onstaj_ogrencisi_kontenjaniChanging(System.Nullable<short> value);
    partial void Onstaj_ogrencisi_kontenjaniChanged();
    partial void Onmakine_parkiChanging(System.Nullable<short> value);
    partial void Onmakine_parkiChanged();
    partial void Onsosyal_hizmetlerChanging(string value);
    partial void Onsosyal_hizmetlerChanged();
    partial void Oneklemek_istediklerinizChanging(string value);
    partial void Oneklemek_istediklerinizChanged();
    #endregion
		
		public Staj()
		{
			this._Durum = default(EntityRef<Durum>);
			this._Firma = default(EntityRef<Firma>);
			this._Kullanici = default(EntityRef<Kullanici>);
			this._Yetkili = default(EntityRef<Yetkili>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_no", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string tc_no
		{
			get
			{
				return this._tc_no;
			}
			set
			{
				if ((this._tc_no != value))
				{
					if (this._Kullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontc_noChanging(value);
					this.SendPropertyChanging();
					this._tc_no = value;
					this.SendPropertyChanged("tc_no");
					this.Ontc_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_kodu", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string staj_kodu
		{
			get
			{
				return this._staj_kodu;
			}
			set
			{
				if ((this._staj_kodu != value))
				{
					this.Onstaj_koduChanging(value);
					this.SendPropertyChanging();
					this._staj_kodu = value;
					this.SendPropertyChanged("staj_kodu");
					this.Onstaj_koduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_baslangic", DbType="DateTime NOT NULL")]
		public System.DateTime staj_baslangic
		{
			get
			{
				return this._staj_baslangic;
			}
			set
			{
				if ((this._staj_baslangic != value))
				{
					this.Onstaj_baslangicChanging(value);
					this.SendPropertyChanging();
					this._staj_baslangic = value;
					this.SendPropertyChanged("staj_baslangic");
					this.Onstaj_baslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_bitis", DbType="DateTime NOT NULL")]
		public System.DateTime staj_bitis
		{
			get
			{
				return this._staj_bitis;
			}
			set
			{
				if ((this._staj_bitis != value))
				{
					this.Onstaj_bitisChanging(value);
					this.SendPropertyChanging();
					this._staj_bitis = value;
					this.SendPropertyChanged("staj_bitis");
					this.Onstaj_bitisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_ctesi", DbType="Bit NOT NULL")]
		public bool staj_ctesi
		{
			get
			{
				return this._staj_ctesi;
			}
			set
			{
				if ((this._staj_ctesi != value))
				{
					this.Onstaj_ctesiChanging(value);
					this.SendPropertyChanging();
					this._staj_ctesi = value;
					this.SendPropertyChanged("staj_ctesi");
					this.Onstaj_ctesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma_id", DbType="Int NOT NULL")]
		public int firma_id
		{
			get
			{
				return this._firma_id;
			}
			set
			{
				if ((this._firma_id != value))
				{
					if (this._Firma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfirma_idChanging(value);
					this.SendPropertyChanging();
					this._firma_id = value;
					this.SendPropertyChanged("firma_id");
					this.Onfirma_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkili_id", DbType="Int NOT NULL")]
		public int yetkili_id
		{
			get
			{
				return this._yetkili_id;
			}
			set
			{
				if ((this._yetkili_id != value))
				{
					if (this._Yetkili.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onyetkili_idChanging(value);
					this.SendPropertyChanging();
					this._yetkili_id = value;
					this.SendPropertyChanged("yetkili_id");
					this.Onyetkili_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_sonuc", DbType="SmallInt NOT NULL")]
		public short staj_sonuc
		{
			get
			{
				return this._staj_sonuc;
			}
			set
			{
				if ((this._staj_sonuc != value))
				{
					this.Onstaj_sonucChanging(value);
					this.SendPropertyChanging();
					this._staj_sonuc = value;
					this.SendPropertyChanged("staj_sonuc");
					this.Onstaj_sonucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_yorum", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string staj_yorum
		{
			get
			{
				return this._staj_yorum;
			}
			set
			{
				if ((this._staj_yorum != value))
				{
					this.Onstaj_yorumChanging(value);
					this.SendPropertyChanging();
					this._staj_yorum = value;
					this.SendPropertyChanged("staj_yorum");
					this.Onstaj_yorumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonuc_tarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> sonuc_tarihi
		{
			get
			{
				return this._sonuc_tarihi;
			}
			set
			{
				if ((this._sonuc_tarihi != value))
				{
					this.Onsonuc_tarihiChanging(value);
					this.SendPropertyChanging();
					this._sonuc_tarihi = value;
					this.SendPropertyChanged("sonuc_tarihi");
					this.Onsonuc_tarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int staj_id
		{
			get
			{
				return this._staj_id;
			}
			set
			{
				if ((this._staj_id != value))
				{
					this.Onstaj_idChanging(value);
					this.SendPropertyChanging();
					this._staj_id = value;
					this.SendPropertyChanged("staj_id");
					this.Onstaj_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum_id", DbType="SmallInt NOT NULL")]
		public short durum_id
		{
			get
			{
				return this._durum_id;
			}
			set
			{
				if ((this._durum_id != value))
				{
					if (this._Durum.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondurum_idChanging(value);
					this.SendPropertyChanging();
					this._durum_id = value;
					this.SendPropertyChanged("durum_id");
					this.Ondurum_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calisan_eleman_sayisi", DbType="SmallInt")]
		public System.Nullable<short> calisan_eleman_sayisi
		{
			get
			{
				return this._calisan_eleman_sayisi;
			}
			set
			{
				if ((this._calisan_eleman_sayisi != value))
				{
					this.Oncalisan_eleman_sayisiChanging(value);
					this.SendPropertyChanging();
					this._calisan_eleman_sayisi = value;
					this.SendPropertyChanged("calisan_eleman_sayisi");
					this.Oncalisan_eleman_sayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lisans_mezunu_personel_sayisi", DbType="SmallInt")]
		public System.Nullable<short> lisans_mezunu_personel_sayisi
		{
			get
			{
				return this._lisans_mezunu_personel_sayisi;
			}
			set
			{
				if ((this._lisans_mezunu_personel_sayisi != value))
				{
					this.Onlisans_mezunu_personel_sayisiChanging(value);
					this.SendPropertyChanging();
					this._lisans_mezunu_personel_sayisi = value;
					this.SendPropertyChanged("lisans_mezunu_personel_sayisi");
					this.Onlisans_mezunu_personel_sayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolumde_calisan_muhendis_sayisi", DbType="SmallInt")]
		public System.Nullable<short> bolumde_calisan_muhendis_sayisi
		{
			get
			{
				return this._bolumde_calisan_muhendis_sayisi;
			}
			set
			{
				if ((this._bolumde_calisan_muhendis_sayisi != value))
				{
					this.Onbolumde_calisan_muhendis_sayisiChanging(value);
					this.SendPropertyChanging();
					this._bolumde_calisan_muhendis_sayisi = value;
					this.SendPropertyChanged("bolumde_calisan_muhendis_sayisi");
					this.Onbolumde_calisan_muhendis_sayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staj_ogrencisi_kontenjani", DbType="SmallInt")]
		public System.Nullable<short> staj_ogrencisi_kontenjani
		{
			get
			{
				return this._staj_ogrencisi_kontenjani;
			}
			set
			{
				if ((this._staj_ogrencisi_kontenjani != value))
				{
					this.Onstaj_ogrencisi_kontenjaniChanging(value);
					this.SendPropertyChanging();
					this._staj_ogrencisi_kontenjani = value;
					this.SendPropertyChanged("staj_ogrencisi_kontenjani");
					this.Onstaj_ogrencisi_kontenjaniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makine_parki", DbType="SmallInt")]
		public System.Nullable<short> makine_parki
		{
			get
			{
				return this._makine_parki;
			}
			set
			{
				if ((this._makine_parki != value))
				{
					this.Onmakine_parkiChanging(value);
					this.SendPropertyChanging();
					this._makine_parki = value;
					this.SendPropertyChanged("makine_parki");
					this.Onmakine_parkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sosyal_hizmetler", DbType="NVarChar(250)")]
		public string sosyal_hizmetler
		{
			get
			{
				return this._sosyal_hizmetler;
			}
			set
			{
				if ((this._sosyal_hizmetler != value))
				{
					this.Onsosyal_hizmetlerChanging(value);
					this.SendPropertyChanging();
					this._sosyal_hizmetler = value;
					this.SendPropertyChanged("sosyal_hizmetler");
					this.Onsosyal_hizmetlerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eklemek_istedikleriniz", DbType="NVarChar(250)")]
		public string eklemek_istedikleriniz
		{
			get
			{
				return this._eklemek_istedikleriniz;
			}
			set
			{
				if ((this._eklemek_istedikleriniz != value))
				{
					this.Oneklemek_istediklerinizChanging(value);
					this.SendPropertyChanging();
					this._eklemek_istedikleriniz = value;
					this.SendPropertyChanged("eklemek_istedikleriniz");
					this.Oneklemek_istediklerinizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Durum_Staj", Storage="_Durum", ThisKey="durum_id", OtherKey="durum_id", IsForeignKey=true)]
		public Durum Durum
		{
			get
			{
				return this._Durum.Entity;
			}
			set
			{
				Durum previousValue = this._Durum.Entity;
				if (((previousValue != value) 
							|| (this._Durum.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Durum.Entity = null;
						previousValue.Stajs.Remove(this);
					}
					this._Durum.Entity = value;
					if ((value != null))
					{
						value.Stajs.Add(this);
						this._durum_id = value.durum_id;
					}
					else
					{
						this._durum_id = default(short);
					}
					this.SendPropertyChanged("Durum");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Staj", Storage="_Firma", ThisKey="firma_id", OtherKey="firma_id", IsForeignKey=true)]
		public Firma Firma
		{
			get
			{
				return this._Firma.Entity;
			}
			set
			{
				Firma previousValue = this._Firma.Entity;
				if (((previousValue != value) 
							|| (this._Firma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firma.Entity = null;
						previousValue.Stajs.Remove(this);
					}
					this._Firma.Entity = value;
					if ((value != null))
					{
						value.Stajs.Add(this);
						this._firma_id = value.firma_id;
					}
					else
					{
						this._firma_id = default(int);
					}
					this.SendPropertyChanged("Firma");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kullanici_Staj", Storage="_Kullanici", ThisKey="tc_no", OtherKey="tc_no", IsForeignKey=true)]
		public Kullanici Kullanici
		{
			get
			{
				return this._Kullanici.Entity;
			}
			set
			{
				Kullanici previousValue = this._Kullanici.Entity;
				if (((previousValue != value) 
							|| (this._Kullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kullanici.Entity = null;
						previousValue.Stajs.Remove(this);
					}
					this._Kullanici.Entity = value;
					if ((value != null))
					{
						value.Stajs.Add(this);
						this._tc_no = value.tc_no;
					}
					else
					{
						this._tc_no = default(string);
					}
					this.SendPropertyChanged("Kullanici");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Yetkili_Staj", Storage="_Yetkili", ThisKey="yetkili_id", OtherKey="yetkili_id", IsForeignKey=true)]
		public Yetkili Yetkili
		{
			get
			{
				return this._Yetkili.Entity;
			}
			set
			{
				Yetkili previousValue = this._Yetkili.Entity;
				if (((previousValue != value) 
							|| (this._Yetkili.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Yetkili.Entity = null;
						previousValue.Stajs.Remove(this);
					}
					this._Yetkili.Entity = value;
					if ((value != null))
					{
						value.Stajs.Add(this);
						this._yetkili_id = value.yetkili_id;
					}
					else
					{
						this._yetkili_id = default(int);
					}
					this.SendPropertyChanged("Yetkili");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarih")]
	public partial class Tarih : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tarih_id;
		
		private System.DateTime _tarih1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontarih_idChanging(int value);
    partial void Ontarih_idChanged();
    partial void Ontarih1Changing(System.DateTime value);
    partial void Ontarih1Changed();
    #endregion
		
		public Tarih()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tarih_id
		{
			get
			{
				return this._tarih_id;
			}
			set
			{
				if ((this._tarih_id != value))
				{
					this.Ontarih_idChanging(value);
					this.SendPropertyChanging();
					this._tarih_id = value;
					this.SendPropertyChanged("tarih_id");
					this.Ontarih_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tarih", Storage="_tarih1", DbType="DateTime NOT NULL")]
		public System.DateTime tarih1
		{
			get
			{
				return this._tarih1;
			}
			set
			{
				if ((this._tarih1 != value))
				{
					this.Ontarih1Changing(value);
					this.SendPropertyChanging();
					this._tarih1 = value;
					this.SendPropertyChanged("tarih1");
					this.Ontarih1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
